CREATE TABLE users (
  user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_hash_id VARCHAR NOT NULL UNIQUE,
  display_name VARCHAR NOT NULL,
  daily_word_limit INTEGER NOT NULL DEFAULT 10,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
