// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type Difficulty string

const (
	DifficultyA1 Difficulty = "A1"
	DifficultyA2 Difficulty = "A2"
	DifficultyB1 Difficulty = "B1"
	DifficultyB2 Difficulty = "B2"
)

func (e *Difficulty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Difficulty(s)
	case string:
		*e = Difficulty(s)
	default:
		return fmt.Errorf("unsupported scan type for Difficulty: %T", src)
	}
	return nil
}

type NullDifficulty struct {
	Difficulty Difficulty
	Valid      bool // Valid is true if Difficulty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDifficulty) Scan(value interface{}) error {
	if value == nil {
		ns.Difficulty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Difficulty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDifficulty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Difficulty), nil
}

type Gender string

const (
	GenderMasculine Gender = "masculine"
	GenderFeminine  Gender = "feminine"
	GenderNeuter    Gender = "neuter"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender
	Valid  bool // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type PartOfSpeech string

const (
	PartOfSpeechNoun         PartOfSpeech = "noun"
	PartOfSpeechVerb         PartOfSpeech = "verb"
	PartOfSpeechAdjective    PartOfSpeech = "adjective"
	PartOfSpeechAdverb       PartOfSpeech = "adverb"
	PartOfSpeechPreposition  PartOfSpeech = "preposition"
	PartOfSpeechPronoun      PartOfSpeech = "pronoun"
	PartOfSpeechConjunction  PartOfSpeech = "conjunction"
	PartOfSpeechArticle      PartOfSpeech = "article"
	PartOfSpeechNumeral      PartOfSpeech = "numeral"
	PartOfSpeechInterjection PartOfSpeech = "interjection"
	PartOfSpeechPhrase       PartOfSpeech = "phrase"
)

func (e *PartOfSpeech) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PartOfSpeech(s)
	case string:
		*e = PartOfSpeech(s)
	default:
		return fmt.Errorf("unsupported scan type for PartOfSpeech: %T", src)
	}
	return nil
}

type NullPartOfSpeech struct {
	PartOfSpeech PartOfSpeech
	Valid        bool // Valid is true if PartOfSpeech is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPartOfSpeech) Scan(value interface{}) error {
	if value == nil {
		ns.PartOfSpeech, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PartOfSpeech.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPartOfSpeech) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PartOfSpeech), nil
}

type Pronoun string

const (
	PronounYo       Pronoun = "yo"
	PronounTu       Pronoun = "tu"
	PronounEl       Pronoun = "el"
	PronounNosotros Pronoun = "nosotros"
	PronounVosotros Pronoun = "vosotros"
	PronounEllos    Pronoun = "ellos"
)

func (e *Pronoun) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Pronoun(s)
	case string:
		*e = Pronoun(s)
	default:
		return fmt.Errorf("unsupported scan type for Pronoun: %T", src)
	}
	return nil
}

type NullPronoun struct {
	Pronoun Pronoun
	Valid   bool // Valid is true if Pronoun is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPronoun) Scan(value interface{}) error {
	if value == nil {
		ns.Pronoun, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Pronoun.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPronoun) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Pronoun), nil
}

type Tense string

const (
	TensePresent     Tense = "present"
	TensePreterite   Tense = "preterite"
	TenseImperfect   Tense = "imperfect"
	TenseFuture      Tense = "future"
	TenseSubjunctive Tense = "subjunctive"
)

func (e *Tense) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Tense(s)
	case string:
		*e = Tense(s)
	default:
		return fmt.Errorf("unsupported scan type for Tense: %T", src)
	}
	return nil
}

type NullTense struct {
	Tense Tense
	Valid bool // Valid is true if Tense is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTense) Scan(value interface{}) error {
	if value == nil {
		ns.Tense, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Tense.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTense) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Tense), nil
}

type AnkiUserWord struct {
	EntryID        int32
	UserID         int32
	WordID         int32
	EaseFactor     float32
	ReviewInterval int32
	LastReviewed   time.Time
	RepCount       int16
	NextReviewDate time.Time
	Revealed       bool
	CreatedAt      sql.NullTime
}

type AnkiWord struct {
	WordID            int32
	Word              string
	PartOfSpeech      PartOfSpeech
	Difficulty        Difficulty
	Gender            NullGender
	EnTranslation     string
	ExampleSentence   sql.NullString
	EnExampleSentence sql.NullString
	CreatedAt         sql.NullTime
}

type QuizAttempt struct {
	AttemptID int32
	UserID    int32
	VerbID    int32
	Tense     Tense
	Perfect   bool
	CreatedAt sql.NullTime
}

type QuizUserVerbProgress struct {
	ProgressID   int32
	UserID       int32
	VerbID       int32
	CurrentTense Tense
	RepCount     int16
	MasteredAt   sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    time.Time
}

type User struct {
	UserID         int32
	UserHashID     string
	DisplayName    string
	DailyWordLimit int32
	CreatedAt      time.Time
}

type Verb struct {
	VerbID int32
	Verb   string
}

type VerbConjugation struct {
	ConjugationID int32
	VerbID        int32
	Tense         Tense
	Pronoun       Pronoun
	CorrectForm   string
}
