// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  user_hash_id,
  display_name
) 
VALUES ($1, $2) 
RETURNING user_id, user_hash_id, display_name, daily_word_limit, created_at
`

type CreateUserParams struct {
	UserHashID  string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.UserHashID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserHashID,
		&i.DisplayName,
		&i.DailyWordLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT display_name, daily_word_limit
FROM users
LIMIT 1
`

type GetUserRow struct {
	DisplayName    string
	DailyWordLimit int32
}

func (q *Queries) GetUser(ctx context.Context) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var i GetUserRow
	err := row.Scan(&i.DisplayName, &i.DailyWordLimit)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
  display_name = COALESCE($1::text, display_name),
  daily_word_limit = COALESCE($2::int, daily_word_limit)
WHERE user_id = (
  SELECT user_id
  FROM users
  LIMIT 1
)
RETURNING display_name, daily_word_limit
`

type UpdateUserParams struct {
	DisplayName    sql.NullString
	DailyWordLimit sql.NullInt32
}

type UpdateUserRow struct {
	DisplayName    string
	DailyWordLimit int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.DisplayName, arg.DailyWordLimit)
	var i UpdateUserRow
	err := row.Scan(&i.DisplayName, &i.DailyWordLimit)
	return i, err
}
