// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  user_hash_id,
  display_name
) 
VALUES ($1, $2) 
RETURNING user_id, user_hash_id, display_name, daily_word_limit, created_at
`

type CreateUserParams struct {
	UserHashID  string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.UserHashID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserHashID,
		&i.DisplayName,
		&i.DailyWordLimit,
		&i.CreatedAt,
	)
	return i, err
}
